# Generated by Django 4.2.7 on 2023-12-11 02:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_broker_client_brokerclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.broker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='BrokerClient',
        ),
    ]
