# Generated by Django 4.2.7 on 2023-12-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_broker_alter_broker_name_delete_brokerclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/uploads/')),
                ('block', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('plot', models.CharField(max_length=45)),
                ('reason', models.CharField(max_length=45)),
                ('signature', models.FileField(null=True, upload_to='files/uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='locaton',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='client',
            name='signature',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
