# Generated by Django 4.2.7 on 2023-12-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_agent_titles_alter_client_locaton_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.agent'),
            preserve_default=False,
        ),
    ]
