# Generated by Django 4.2.7 on 2023-12-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_broker_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Amount_paid_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.AddField(
            model_name='client',
            name='Amount_paid',
            field=models.IntegerField(default='60000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='commision',
            field=models.IntegerField(default='60000'),
            preserve_default=False,
        ),
    ]
