# Generated by Django 4.2.7 on 2023-12-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='signature',
        ),
        migrations.AddField(
            model_name='titles',
            name='price',
            field=models.IntegerField(default='20000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titles',
            name='price_paid',
            field=models.IntegerField(default='1000'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TitleTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.titles')),
            ],
        ),
    ]
