# Generated by Django 4.2.7 on 2023-12-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_titles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='reason',
            field=models.TextField(max_length=250),
        ),
    ]
