# Generated by Django 4.2.7 on 2024-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_titles_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(default='0705099093', max_length=45),
            preserve_default=False,
        ),
    ]
